//TODO
function throwException(message){
    alert(message);
}